# Version Number
version: 20240116

# Site Info
title: KVIrc.net - The Visual IRC Client
email: kvirc@kvirc.net
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
domain: kvirc-net.github.io
url: "https://kvirc-net.github.io"
github_username: kvirc

# Build settings
theme: minima
markdown: GFM
plugins:
  - jekyll-feed
  - jekyll-minifier
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
sass:
  style: compressed
strict_front_matter: true
paginate: 15
jekyll-minifier:
  compress_javascript: true
  #  compress_css: false
  #  exclude: ['jquery-3.7.0.slim.min.js','bootstrap.bundle.js','bootstrap.bundle.js.map','bootstrap.bundle.min.js','bootstrap.bundle.min.js.map','respond.js']
#  exclude:
#    - jquery-3.7.0.slim.min.js
#    - bootstrap.bundle.js
#    - bootstrap.bundle.js.map
#    - bootstrap.bundle.min.js
#    - bootstrap.bundle.min.js.map
#    - respond.js
  uglifier_args:
    harmony: true